# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
 
name: Build and deploy ASP.Net Core app to Azure Web App - multiten-webapp-01
 
on:
  push:
    branches:
      - dev
  workflow_dispatch:
 
env:
  AZURE_WEBAPP_NAME: multiten-webapp-01    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'
  BUILD_D_PATH: '/home/runner/work/MultiTenantApp/MultiTenantApp/samples/net6.0/IdentitySample/'
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true
          
      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef --version 6.0.6
 
      - name: Build with dotnet
        run: dotnet build samples/net6.0/IdentitySample/IdentitySample.csproj --configuration Release
 
      - name: Restore dependencies
        run: dotnet restore samples/net6.0/IdentitySample/IdentitySample.csproj
        
      - name: Run Entity Framework Core migrations
        run: dotnet ef database update --project samples/net6.0/IdentitySample/IdentitySample.csproj --startup-project samples/net6.0/IdentitySample/IdentitySample.csproj
 
      - name: dotnet publish
        run: dotnet publish -c Release -f net6.0 --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
 
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DC1BBD7A7B994DAB8A2802CB9D2C6238  }} # Define secret variable in repository settings as per action documentation
          package: '/home/runner/work/MultiTenantApp/MultiTenantApp/samples/net6.0/IdentitySample/myapp/'

      - name: Perform copy file operation for SQLite
        shell: pwsh
        run: |    
          # Output the GitHub workspace directory for debugging
          echo "${{ github.workspace }}"
          
          # Create the Data directory if it doesn't exist
          New-Item -Path '${{ env.BUILD_D_PATH }}/myapp/Data' -ItemType Directory -Force
      
          # Copy the SQLite database files
          Copy-Item -Path "${{ github.workspace }}/samples/net6.0/IdentitySample/Data/SharedIdentity.db" -Destination '${{ env.BUILD_D_PATH }}/myapp/Data' -Force
          Copy-Item -Path "${{ github.workspace }}/samples/net6.0/IdentitySample/Data/InitechIdentity.db" -Destination '${{ env.BUILD_D_PATH }}/myapp/Data' -Force
